default_language_version:
  python: python3.14
  # Pin Node LTS for Biome
  node: 22.20.0
default_install_hook_types: ["commit-msg", "pre-commit"]
default_stages: ["pre-commit"]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext", "md"]
      - id: check-case-conflict

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: ["--py314-plus"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: ["django-stubs[compatible-mypy]"]
        exclude: '\.pdbrc$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        args: ["--config", ".markdownlint-cli2.yaml"]

  - repo: https://github.com/biomejs/pre-commit
    rev: v2.2.4
    hooks:
      - id: biome-check
        exclude: '(\.*htmx.*\.min\.js|.*/?mvp\.css)'

  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: 1.6.0
    hooks:
      - id: djade
        args: [--target-version, "5.2"]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.28.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.2"]

  - repo: https://github.com/crate-ci/typos
    rev: v1.37.2
    hooks:
      - id: typos
        # Overwrite <https://github.com/crate-ci/typos/blob/master/.pre-commit-hooks.yaml>
        # to avoid default `--write-changes` flag - report findings only.
        args: [--force-exclude]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        stages: ["commit-msg"]
        additional_dependencies: ["@commitlint/config-conventional"]
