# Run checks and test suite. Intended to be run ahead of building / containerising the app.
#
# Usage:
# ```
# jobs:
#   checks:
#     uses: ./.github/workflows/_pre-build-checks.yaml
#     with:
#       django_checks_deploy: 'false' | 'true'
# ```
name: Pre-build checks

on:
  workflow_call:
    inputs:
      django_checks_deploy:
          description: 'Run checks in deploy mode'
          type: string
          default: 'false'
          required: false
    secrets:
      DJANGO_SECRET_KEY:
        required: false

jobs:
  pre_commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/pre-commit

  generate-nox-sessions:
    runs-on: ubuntu-24.04
    outputs:
      session: ${{ steps.set-matrix.outputs.session }}
    steps:
      - uses: actions/checkout@v5
      - name: Cache nox session list
        id: cache-sessions
        uses: actions/cache@v4
        with:
          path: .nox-sessions.json
          key: nox-sessions-${{ runner.os }}-${{ hashFiles('noxfile.py', 'pyproject.toml') }}
      - uses: wntrblm/nox@2025.10.16
        if: steps.cache-sessions.outputs.cache-hit != 'true'
      - id: set-matrix
        shell: bash
        env:
          CACHE_SESSIONS_HIT: ${{ steps.cache-sessions.outputs.cache-hit }}
        run: |
          if [[ $CACHE_SESSIONS_HIT == "true" ]]; then
            sessions_json="$(cat .nox-sessions.json)"
          else
            sessions_json="$(
              nox --list \
                | grep -E '^[*-] ' \
                | cut -d' ' -f2 \
                | jq -R -s -c 'split("\n")[:-1]'
            )"
            echo "$sessions_json" > .nox-sessions.json
          fi
          echo "session=$sessions_json" >> "$GITHUB_OUTPUT"

  test:
    needs:
      - pre_commit
      - generate-nox-sessions
    strategy:
      fail-fast: false
      matrix:
        session: ${{ fromJson(needs.generate-nox-sessions.outputs.session) }}
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: test_testdjereo
          POSTGRES_USER: test_testdjereo
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.2"
          enable-cache: true
      - uses: wntrblm/nox@2025.10.16
      - run: nox --session "${{ matrix.session }}"

  django:
    needs:
      - pre_commit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/django-checks
        with:
          deploy: ${{ inputs.django_checks_deploy }}
          django-secret-key: ${{ secrets.DJANGO_SECRET_KEY }}
