# Pull Request pipeline
# Runs when a commit on a feature branch is pushed up to GitHub.
name: PR

on:
  # TODO: reinstate
  #push:
  #  branches-ignore:
  #    - main
  #pull_request:
  #  branches-ignore:
  #    - main
  push:
    tags:
      - 'never'

jobs:
  checks:
    uses: ./.github/workflows/_pre-build-checks.yaml
